workflows:
  android-workflow:
    name: Build Android Debug APK
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Force fix pubspec.yaml
        script: |
          # Supprime brutalement les lignes qui pointent vers des dossiers locaux inexistants
          sed -i '/path: figma_squircle/d' pubspec.yaml
          sed -i '/path: liquid_progress_indicator_v2/d' pubspec.yaml
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build debug APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
